### ISSUE TITLE
Extending the same base class in two different objects creates weird data duplication problems

### ISSUE THREAD

**Issue by subnetmarco** [rxi/classic#2]
This can be better explained by looking at the following example, where I create three different classes: a base class called `BaseClass`, that's being extended by both `ClassOne` and `ClassTwo`.

``` lua
Object = require "classic"

-- BaseClass provides a say() method
local BaseClass = Object:extend()
function BaseClass:new(name)
  self._name = name
end
function BaseClass:say()
  print("Hello " .. self._name)
end

-- ClassOne extends BaseClass
local ClassOne = BaseClass:extend()
function ClassOne:new()
  ClassOne.super:new("Mark")
end

-- ClassTwo extends BaseClass
local ClassTwo = BaseClass:extend()
function ClassTwo:new()
  ClassTwo.super:new("John")
end

-- ===================================
-- =       Let's try it out:         =
-- ===================================

local class_one = ClassOne()
local class_two = ClassTwo()
class_one:say()
class_two:say()
```

This doesn't work, instead of printing

```
Hello Mark
Hello John
```

it prints:

```
Hello John
Hello John
```

It seems like the initialization of `ClassTwo()` overwrites the `_name` variable in `ClassOne()`.

Why is this happening?

**Comment by subnetmarco** [comment]
Once the pull request #3 has been merged, this issue can be considered resolved.

**Comment by rxi** [comment]
You're making a mistake in regard to the following line (and the other similar case), where you call the object super's new() function:

``` lua
  ClassOne.super:new("Mark")
```

The function should be passed the object (`self` in this context), where as the use of the `:` operator in your example is passing `super` such that the `new()` function is operating on the super-class table rather than the object table, resulting in odd behaviour. This line should be as follows:

``` lua
  ClassOne.super.new(self, "Mark")
```

https://github.com/rxi/classic#extending-an-existing-class
